//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibddApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int PenaltyId { get; set; }
        public string VIN { get; set; }
        public Nullable<int> IdViolation { get; set; }
        public Nullable<int> IdTPU { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual TPU TPU { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
